// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqfrnzlmporencfbofoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxZnJuemxtcG9yZW5jZmJvZm9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTQxMzEsImV4cCI6MjA2ODY5MDEzMX0.D-XBjC1Dsa_eGj4Catws3i_eQe3DjXlc79WT-E5YvAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});